econ_dict = {'euro area': 'euroarea',
               'dual mandate': 'dualmandate',
               'united kingdom': 'unitedkingdom',
               'united states': 'unitedstates',
               'per cent': 'percent',
               'forward guidance': 'forwardguidance',
               'basis points': 'basispts',
               'nonfarm payroll': 'nonfarmpayroll',
                'non farm payroll': 'nonfarmpayroll',
               'federal funds rate': 'ffr',
               'funds rate': 'fundsrate',
               'interest rates': 'interestrate',
               'interest rate': 'interestrate',
               'economic growth': 'econgrowth',
               'monetary policy': 'monetarpol',
               'unemployment rate': 'unemprate',
               'inflation expectations': 'inflexp',
               'inflation expectation': 'inflexp',
               'federal reserve': 'fedreserve',
               'labor market': 'labormkt',
                'labor markets': 'labormarket',
               'foreign exchange': 'forex',
               'treasury securities': 'treasurysecurities',
               'new york': 'nyc',
                'trade deficit': 'tradedeficit',
                'real gdp': 'realgdp',
                'mortgagebacked securities': 'mbs',
                'reserve markets': 'reservemarket',
                'reserve market': 'reservemarket',
                'real estate': 'realestate',
                'capital spending': 'capitalspend',
                'fiscal policy': 'fiscalpol',
                'aggregate demand': 'aggdemand',
                'consumer price index': 'cpi',
                'retail price index': 'rpi',
                'mortgage rates': 'mortgagerate',
                'mortgage rate': 'mortgagerate',
                'money market': 'moneymkt',
                'commodity prices': 'commodityprice',
                'household spending': 'householdspend',
                'consumer sentiment': 'consumersentiment',
                'consumer confidence': 'consumerconfid',
                'corporate bonds': 'corporatebond',
                'housing market': 'housingmkt',
                'stock market': 'stockmkt',
                'capacity utilization': 'capacitutil',
                'labor force': 'laborforce',
                'federal open market': 'fedopenmkt',
                'consumer price inflation': 'cpinflat',
                'wage rates': 'wagerate',
                'green book': 'greenbook',
                'oil price': 'oilprice',
                'oil prices': 'oilprice',
                'basis points': 'basispoints'
               }

